#define GENERAL_TEST_COMMUNICATION_FROM_NODE1 (0x0F) // All 1s
#define GENERAL_TEST_COMMUNICATION_FROM_NODE2 (0x0E)
#define JOYSTICK_INFO (0x04)

#define PHASE1 (5)
#define PHASE2 (5)
#define PROPAG (2)
#define SJW (3)
#define BAUDRATE (250000 * 16)